services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    expose:
      - "3306"
    volumes:
      - /home/grisha/42Proj/Inception/data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

# volumes:
#   mariadb:
#     driver_opts:
#       type: 'none'
#       o: bind
#       device: /home/grisha/42Proj/Inception/data

networks:
  inception:
    name: inception-network
    driver: bridge